version: "3"

services:

  postgres:
    image: postgres
    container_name: schoolhub-postgres
    expose:
      - "5432"
    ports:
      - "5433:5432"
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5





