server:
  port: 0

spring:
  cloud:
    config:
      enabled: false

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/order_service_db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: order-service

logging:
  file:
    name: logs/order-service.log

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      inventory:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter:
    instances:
      inventory:
        timeout-duration: 3s

  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 5s

