spring:
  application:
    name: product-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: productDB


  cloud:
    config:
      enabled: false
server:
  port: 9999


