spring:
  application:
    name: product-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: productDB


  cloud:
    config:
      enabled: false
server:
  port: 0

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


