server:
  port: 0

spring:
  cloud:
    config:
      enabled: false

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/inventory_service_db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: inventory-service

logging:
  file:
    name: logs/inventory-service.log

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/